// Generated by dts-bundle v0.7.3

export function crawling(gl?: string, gh?: string): Promise<VideoTrendFeedInfos>;
export default crawling;

export interface VideoTrendFeedInfo {
    videoId: string;
    thumbnail?: string;
    title: string;
    channelId: string;
    rank: number;
    type: 'shorts' | 'video';
}
export type VideoTrendFeedInfos = VideoTrendFeedInfo[];
export enum CrawlingErrorCode {
    Normal = 0,
    PlayerResponse = 1,
    InitalData = 2,
    InitalContinueData = 3,
    Unknown = 4
}
export class CrawlingError extends Error {
    code: CrawlingErrorCode;
    name: string;
    constructor(code: CrawlingErrorCode, message?: string);
}

